# Generated by Django 5.2.5 on 2025-09-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csieCampApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BingoGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='teamprofile',
            name='fixed_savings',
            field=models.IntegerField(default=-1),
        ),
    ]
