# Generated by Django 5.2.5 on 2025-09-06 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csieCampApp', '0004_commentboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentboard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
